# Generated by Django 3.0.1 on 2020-01-05 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChineseCharacters',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('simplified', models.CharField(blank=True, default='', max_length=10, unique=True, verbose_name='简体中文')),
                ('traditional', models.CharField(blank=True, default='', max_length=10, verbose_name='繁体中文')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('allusion', models.TextField(blank=True, default='', verbose_name='文字典故')),
                ('pinyin', models.CharField(blank=True, default='', max_length=20, verbose_name='拼音')),
                ('img_file', models.ImageField(blank=True, default='', upload_to='cha/', verbose_name='存储位置')),
            ],
        ),
    ]
