<<<<<<< HEAD
# Generated by Django 3.0.1 on 2020-01-06 09:24
=======
# Generated by Django 3.0.1 on 2020-01-06 09:26
>>>>>>> b8400518c975d42e9c5dae4bb6799595fe827436

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChineseCharacters',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('simplified', models.CharField(blank=True, default='', max_length=10, unique=True, verbose_name='简体中文')),
                ('traditional', models.CharField(blank=True, default='', max_length=10, verbose_name='繁体中文')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('allusion', models.TextField(blank=True, default='', verbose_name='文字典故')),
                ('pinyin', models.CharField(blank=True, default='', max_length=100, verbose_name='拼音')),
                ('img_file', models.ImageField(blank=True, default='', upload_to='cha/', verbose_name='存储位置')),
            ],
        ),
        migrations.CreateModel(
            name='Shi',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('author', models.CharField(blank=True, default='', max_length=50, verbose_name='作者')),
                ('title', models.CharField(blank=True, default='', max_length=200, verbose_name='诗名')),
                ('content', models.TextField(blank=True, default='', verbose_name='诗内容')),
                ('chapter', models.CharField(blank=True, default='', max_length=10, verbose_name='篇章')),
                ('section', models.TextField(blank=True, default='', verbose_name='卷')),
                ('dynasty', models.CharField(blank=True, default='', max_length=10, verbose_name='朝代')),
            ],
        ),
        migrations.CreateModel(
            name='ShiJing',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('chapter', models.CharField(blank=True, default='', max_length=10, verbose_name='作者')),
                ('title', models.CharField(blank=True, default='', max_length=100, verbose_name='诗名')),
                ('content', models.TextField(blank=True, default='', verbose_name='诗经内容')),
                ('section', models.CharField(blank=True, default='', max_length=10, verbose_name='朝代')),
            ],
        ),
        migrations.CreateModel(
            name='SongCi',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('author', models.CharField(blank=True, default='', max_length=10, verbose_name='作者')),
                ('rhythmic', models.TextField(blank=True, default='', verbose_name='词牌名')),
                ('content', models.TextField(blank=True, default='', verbose_name='词内容')),
                ('dynasty', models.CharField(blank=True, default='宋', max_length=10, verbose_name='朝代')),
                ('category', models.CharField(blank=True, default='词', max_length=10)),
            ],
        ),
    ]
