# Generated by Django 3.0.1 on 2020-01-06 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hanzi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shi',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('author', models.CharField(blank=True, default='', max_length=10, verbose_name='作者')),
                ('title', models.CharField(blank=True, default='', max_length=10, verbose_name='诗名')),
                ('content', models.TextField(blank=True, default='', verbose_name='诗内容')),
                ('chapter', models.CharField(blank=True, default='', max_length=10, verbose_name='篇章')),
                ('section', models.TextField(blank=True, default='', verbose_name='卷')),
            ],
        ),
        migrations.CreateModel(
            name='ShiJing',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('author', models.CharField(blank=True, default='', max_length=10, verbose_name='作者')),
                ('title', models.CharField(blank=True, default='', max_length=10, verbose_name='诗名')),
                ('content', models.TextField(blank=True, default='', verbose_name='诗经内容')),
                ('dynasty', models.CharField(blank=True, default='', max_length=10, verbose_name='朝代')),
            ],
        ),
        migrations.CreateModel(
            name='SongCi',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('author', models.CharField(blank=True, default='', max_length=10, verbose_name='作者')),
                ('rhythmic', models.CharField(blank=True, default='', max_length=10, verbose_name='词牌名')),
                ('content', models.TextField(blank=True, default='', verbose_name='词内容')),
                ('dynasty', models.CharField(blank=True, default='宋', max_length=10, verbose_name='朝代')),
                ('category', models.CharField(blank=True, choices=[('shi', '诗'), ('ci', '词')], max_length=10)),
            ],
        ),
    ]
