# Generated by Django 3.0.1 on 2020-01-07 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hanzi', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shi',
            new_name='Poem',
        ),
    ]
