# Generated by Django 3.0.1 on 2019-12-30 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hanzi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chinesecharacters',
            name='img_file',
            field=models.FileField(blank=True, default='', upload_to='cha/', verbose_name='存储位置'),
        ),
    ]
