# Generated by Django 3.0.1 on 2019-12-30 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hanzi', '0004_auto_20191230_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chinesecharacters',
            name='img_file',
            field=models.ImageField(blank=True, default='', upload_to='cha/', verbose_name='存储位置'),
        ),
    ]
